
import java.awt.Label;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sebastianderooy
 */
public class ExpensesUI extends javax.swing.JFrame {

    /**
     * Creates new form ExpensesUI
     */
    public ExpensesUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblExpenses = new javax.swing.JLabel();
        btnAddExpense = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAName = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAAmount = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtTotalAmount = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));

        lblExpenses.setBackground(new java.awt.Color(255, 255, 255));
        lblExpenses.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        lblExpenses.setForeground(new java.awt.Color(0, 102, 255));
        lblExpenses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpenses.setText("EXPENSES");

        btnAddExpense.setBackground(new java.awt.Color(51, 102, 255));
        btnAddExpense.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnAddExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnAddExpense.setText("+");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        txtAmount.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(0, 102, 255));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 255));

        lblName.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 255));
        lblName.setText("Name of expense");

        lblAmount.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(0, 102, 255));
        lblAmount.setText("Expense amount");

        lblAdd.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(0, 153, 255));
        lblAdd.setText("Add Expense");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAName.setEditable(false);
        txtAName.setColumns(20);
        txtAName.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtAName.setForeground(new java.awt.Color(0, 0, 255));
        txtAName.setRows(5);
        jScrollPane1.setViewportView(txtAName);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAAmount.setEditable(false);
        txtAAmount.setColumns(20);
        txtAAmount.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtAAmount.setForeground(new java.awt.Color(0, 102, 255));
        txtAAmount.setRows(5);
        jScrollPane2.setViewportView(txtAAmount);

        btnClear.setBackground(new java.awt.Color(0, 153, 255));
        btnClear.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(0, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtTotalAmount.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtTotalAmount.setForeground(new java.awt.Color(0, 102, 255));

        txtTotal.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 255));
        txtTotal.setText("Total Expenses");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<--");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtTotal))
                .addGap(24, 24, 24)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit)
                            .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClear))))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblAmount)
                        .addGap(18, 18, 18)
                        .addComponent(lblAdd)))
                .addGap(17, 17, 17))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblExpenses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblExpenses))
                .addGap(9, 9, 9)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblAmount)
                    .addComponent(lblAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddExpense))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
        //getting name and amount of expense before adding
        String name = txtName.getText();
        int amount = Integer.parseInt(txtAmount.getText());
        String am = txtAmount.getText().trim();
        
        //previously entered values are saved
        String nameA = txtAName.getText();
        String amountA = txtAAmount.getText();
        
          boolean valid = true;
      
        int count = 0;
        //validates amount entered for expense
       for (int i = 0; i < am.length(); i++) 
        {
            
            char letter = am.charAt(i);
            int l = (int)(letter);
            if (l >= 48 && l <= 57)
            {
                if (l == 32)
                {
                    count++;
                }
            } else {
                valid = false;
            }
        }
        
        if (valid)
        {
            //adds new expense to text area
        if (amountA.isEmpty())
        {
            txtAName.setText(name);
            txtAAmount.setText("" + amount);
        } else {
            txtAName.setText(nameA + "\n" + name);
        txtAAmount.setText(amountA + "\n" + amount);
        }
        }
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //clears text area of all expenses
        txtAName.setText("");
        txtAAmount.setText("");
        txtTotalAmount.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        Scanner sc = new Scanner(txtAAmount.getText());
        String amount;
        int total = 0;
        int a;
        //calculates total 
        while (sc.hasNextLine())
        {
            amount = sc.nextLine();
            a = Integer.parseInt(amount);
            total += a;
        }
        txtTotalAmount.setText("" + total);
        
        
         String budget = "";
         
        
         
            try 
            {
                //gets current budget
            Scanner scf = new Scanner(new File("/users/SebastiandeRooy/FinBud/CurrentBudget.txt"));
            budget = scf.nextLine();
            } catch (FileNotFoundException e)
            {
                System.out.println("File not found");
            }
            
            //sets total expenses in database
            Budget bud = new Budget(budget);
            bud.setExpenses(total);
            
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //opens budgetui jframe
        BudgetUI bud = new BudgetUI();
        bud.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpensesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpensesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpensesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpensesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpensesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txtAAmount;
    private javax.swing.JTextArea txtAName;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
