/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author sebastianderooy
 */
public class LogIn extends javax.swing.JFrame {

    ImageIcon logo = new ImageIcon("Logo2.png");
    
    /**
     * Creates new form NewJFrame
     */
    public LogIn() {
        initComponents();
        //setting up frame
        lblLogo.setText("");
        lblLogo.setIcon(logo);
        lblNameError.setText("");
        lblPasswordError.setText("");
        lblError.setText("");
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogIn = new javax.swing.JPanel();
        lblNameErr = new javax.swing.JLabel();
        lblLogIn = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblSignUp = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPasswordError = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        pswrdPassword = new javax.swing.JPasswordField();
        lblNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNameErr.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblNameErr.setForeground(new java.awt.Color(255, 0, 51));

        lblLogIn.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(51, 51, 255));
        lblLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogIn.setText("LOG");
        lblLogIn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblLogIn.setMaximumSize(new java.awt.Dimension(78, 25));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("jLabel1");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(0, 153, 255));
        btnSignUp.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Register");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblSignUp.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(0, 153, 255));
        lblSignUp.setText("If not Registered already");

        lblError.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Error");
        lblError.setAlignmentY(0.0F);

        btnLogIn.setBackground(new java.awt.Color(51, 102, 255));
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        lblName.setForeground(new java.awt.Color(51, 51, 255));
        lblName.setText("Name");

        lblPassword.setForeground(new java.awt.Color(51, 51, 255));
        lblPassword.setText("Password");

        lblPasswordError.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        lblPasswordError.setText("P");

        lblI.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        lblI.setForeground(new java.awt.Color(51, 102, 255));
        lblI.setText("IN");

        pswrdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrdPasswordActionPerformed(evt);
            }
        });

        lblNameError.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 51, 51));
        lblNameError.setText("error");

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInLayout.createSequentialGroup()
                                .addComponent(lblSignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSignUp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(31, 31, 31)
                                .addComponent(pswrdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(54, 54, 54)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(lblLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblI))
                            .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(btnLogIn)))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(lblLogo)
                .addGap(49, 49, 49)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblName))
                    .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblPassword))
                    .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pswrdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addGap(18, 18, 18)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignUp)
                    .addComponent(btnSignUp))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        //getting name and password input
        String name = txtName.getText().toLowerCase();
        String password = pswrdPassword.getText().toLowerCase();
        
        boolean nvalid = true;
        boolean pvalid = true;
        boolean real = false;
        boolean match = false;
        
       //validates presence
       if (name.length() == 0)
       {
           nvalid = false;
       }
       if (password.length() == 0)
       {
           pvalid = false;
       }
            
        //validates name
        for (int i = 0; i < name.length(); i++) 
        {
           
            if (nvalid)
            {
            char c = name.charAt(i);
            if ((c >= 65 && c <= 90) || (c >= 97 && c <= 122) || c == 32)
            {
                nvalid = true;
            } else {
                nvalid = false;
            }
            }
        }
        
        //validates password
        for (int i = 0; i < password.length(); i++) 
        {
            if (pvalid)
            {
            char c = password.charAt(i);
            if ((c >= 65 && c <= 90) || (c >= 97 && c <= 122) || (c >= 48 && c <= 57) || c == 32)
            {
                pvalid = true;
            } else {
                pvalid = false;
            }
            }
        }
        
         //displays whether name is valid
            if (nvalid)
        {
            lblNameError.setText("");
        } else {
            lblNameError.setText("Invalid characters entered");
        }
        
            //displays whether password is valid
        if (pvalid)
        {
            lblPasswordError.setText("");
        } else {
            lblPasswordError.setText("Invalid characters entered");
        }
        
        if (nvalid && pvalid)
        {
            
            String databaseURL = "jdbc:ucanaccess:///Users/SebastiandeRooy/FinBud/FinBudDB.accdb";
        
        
            try {
            Connection connection = DriverManager.getConnection(databaseURL);
            
            System.out.println("Connected");
            
           String sql = "Select * from tblUser";
            
        
        
            Statement state = connection.createStatement();
            ResultSet result = state.executeQuery(sql);
            
            String[] str = new String[100];
            int i = 0;
                
            //enters all usernames into an array
            while (result.next())
            {
                String n = result.getString("UserName").toLowerCase();
                if (!n.isEmpty())
                {
                str[i] = n;
                i++;
                }
            }    
            connection.close();

       
            
            
            //checks whether the user exists
                for (int j = 0; j < str.length; j++) 
                {
                    if (name.equals(str[j]))
                    {
                        real = true;
                    }
                        
                }
                
                } catch (SQLException ex) {
             Logger.getLogger(DBUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
                //checks whether entered password is correct
                if (real)
                {
                    
                    User user = new User(name);
                    String p = user.getPassword();
                    
                if (password.equals(p))
                {
                    match = true;
                }
                    
            
                        
                } else {
                    lblError.setText("User does not exist, register required");
                }
                    
            
            
        
        }
        
        if (match)
        {       
            //prints username to current user textfile
            try {
                PrintWriter outFile = new PrintWriter
        (new FileWriter("/users/SebastiandeRooy/FinBud/CurrentUser.txt"));
            outFile.print(name);
            outFile.close();
            } catch (IOException ex) {
                System.out.println("Error");
            }
            
            //opens profile jframe
            Profile profile = new Profile();
            profile.setUser(name);
            profile.setVisible(true);
            dispose(); 
        } else if (!match && real){
            lblError.setText("Incorrect Password");
        }
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        //opens register jframe
        Register reg = new Register();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void pswrdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswrdPasswordActionPerformed
        
    }//GEN-LAST:event_pswrdPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameErr;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPasswordField pswrdPassword;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
