
import java.awt.Label;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sebastianderooy
 */
public class Profile extends javax.swing.JFrame {

    ImageIcon logo = new ImageIcon("Logo2.png");
    
    /**
     * Creates new form Profile
     */
    
    //method to change user label to user name
     public void setUser(String u)
    {
        lblUser.setText(u);
    }
    
    public Profile() {
        initComponents();
        //setting up frame
        lblLogo.setText("");
        lblLogo.setIcon(logo);
        
        String databaseURL = "jdbc:ucanaccess:///Users/SebastiandeRooy/FinBud/FinBudDB.accdb";
        
        try {
            Connection connection = DriverManager.getConnection(databaseURL);
            
            System.out.println("Connected");
            String username = "";
            try
            {
                //gets current user from textfile
                Scanner scf = new Scanner(new File("/Users/SebastiandeRooy/FinBud/CurrentUser.txt"));
                username = scf.nextLine();
            } catch (FileNotFoundException e)
            {
                System.out.println("File not Found");
            }
            System.out.println(username);
            //sets label to current user
            lblUser.setText(username);
            
            //gets all budgets that are connected to current user
             String sql = "SELECT BUDGETNAME \n" +
                    "FROM `tblBudget` \n" +
                    "INNER JOIN\n" +
                    "	(`tblID` \n" +
                    "	INNER JOIN\n" +
                    "	`tblUser` \n" +
                    "	ON tblID.`UserID` = tblUser.`UserID` \n" +
                    "	)\n" +
                    "ON tblBudget.`BudgetID` = tblID.`BudgetID`\n" +
                    "WHERE USERNAME = '" + username + "'";
          
             Statement state = connection.createStatement();
             ResultSet result = state.executeQuery(sql);
        
             String[] str = new String[5];
             int i = 0;
             
            
            //puts budgetnames into array
            while (result.next())
            {
                String n = result.getString("BudgetName");
                if (!n.isEmpty())
                {
                str[i] = n;
                i++;
                }
            }    
            
             for (int j = 0; j < i;j++) 
             {
                 System.out.println(str[j]);
             }
            
             //enters budgets into possible budget slots
            if (i == 0)
            {
                btnEdit1.setVisible(false);
                btnEdit2.setVisible(false);
                btnEdit3.setVisible(false);
                btnDelete1.setVisible(false);
                btnDelete2.setVisible(false);
                btnDelete3.setVisible(false);
            } else if (i == 1)
            {
                btnEdit2.setVisible(false);
                btnEdit3.setVisible(false);
                btnDelete2.setVisible(false);
                btnDelete3.setVisible(false);
                
                btnCreate1.setVisible(false);
                txtBudget1.setText(str[0]);
            } else if (i == 2)
            {
                btnEdit3.setVisible(false);
                btnDelete3.setVisible(false);
                
                btnCreate1.setVisible(false);
                btnCreate2.setVisible(false);
                txtBudget1.setText(str[0]);
                txtBudget2.setText(str[1]);
            } else if (i == 3)
            {
                btnCreate1.setVisible(false);
                btnCreate2.setVisible(false);
                btnCreate3.setVisible(false);
                txtBudget1.setText(str[0]);
                txtBudget2.setText(str[1]);
                txtBudget3.setText(str[2]);
            }
            
        } catch (SQLException ex)
        {
            System.out.println("Error");
        }
        
    }

   
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProfile = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblBudgets = new javax.swing.JLabel();
        txtBudget1 = new javax.swing.JTextField();
        txtBudget2 = new javax.swing.JTextField();
        txtBudget3 = new javax.swing.JTextField();
        lblBudget1 = new javax.swing.JLabel();
        lblBudget2 = new javax.swing.JLabel();
        lblBudget3 = new javax.swing.JLabel();
        btnCreate1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnCreate2 = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        btnCreate3 = new javax.swing.JButton();
        btnEdit3 = new javax.swing.JButton();
        btnDelete3 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.setForeground(new java.awt.Color(0, 153, 255));

        lblLogo.setText("jLabel1");

        lblUser.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 102, 255));
        lblUser.setText("User");

        lblBudgets.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblBudgets.setForeground(new java.awt.Color(0, 153, 255));
        lblBudgets.setText("Budgets:");

        txtBudget1.setEditable(false);
        txtBudget1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        txtBudget1.setForeground(new java.awt.Color(0, 153, 255));
        txtBudget1.setText("[Budget Slot 1]");

        txtBudget2.setEditable(false);
        txtBudget2.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        txtBudget2.setForeground(new java.awt.Color(0, 153, 255));
        txtBudget2.setText("[Budget Slot 2]");

        txtBudget3.setEditable(false);
        txtBudget3.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        txtBudget3.setForeground(new java.awt.Color(0, 153, 255));
        txtBudget3.setText("[Budget Slot 3]");

        lblBudget1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblBudget1.setForeground(new java.awt.Color(0, 153, 255));
        lblBudget1.setText("1");

        lblBudget2.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblBudget2.setForeground(new java.awt.Color(0, 153, 255));
        lblBudget2.setText("2");

        lblBudget3.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        lblBudget3.setForeground(new java.awt.Color(0, 153, 255));
        lblBudget3.setText("3");

        btnCreate1.setBackground(new java.awt.Color(0, 102, 255));
        btnCreate1.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        btnEdit1.setBackground(new java.awt.Color(0, 102, 255));
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(0, 0, 255));
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnCreate2.setBackground(new java.awt.Color(0, 102, 255));
        btnCreate2.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate2.setText("Create");
        btnCreate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate2ActionPerformed(evt);
            }
        });

        btnEdit2.setBackground(new java.awt.Color(0, 102, 255));
        btnEdit2.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit2.setText("Edit");
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });

        btnDelete2.setBackground(new java.awt.Color(0, 0, 255));
        btnDelete2.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete2.setText("Delete");

        btnCreate3.setBackground(new java.awt.Color(0, 102, 255));
        btnCreate3.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate3.setText("Create");
        btnCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate3ActionPerformed(evt);
            }
        });

        btnEdit3.setBackground(new java.awt.Color(0, 102, 255));
        btnEdit3.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit3.setText("Edit");
        btnEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit3ActionPerformed(evt);
            }
        });

        btnDelete3.setBackground(new java.awt.Color(0, 0, 255));
        btnDelete3.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete3.setText("Delete");

        btnLogOut.setBackground(new java.awt.Color(0, 153, 255));
        btnLogOut.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut))
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(lblUser))
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblBudgets))
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBudget1)
                                    .addComponent(lblBudget2)
                                    .addComponent(lblBudget3))
                                .addGap(18, 18, 18)
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProfileLayout.createSequentialGroup()
                                        .addComponent(txtBudget2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCreate2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete2))
                                    .addGroup(pnlProfileLayout.createSequentialGroup()
                                        .addComponent(txtBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCreate1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete1))
                                    .addGroup(pnlProfileLayout.createSequentialGroup()
                                        .addComponent(txtBudget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCreate3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete3)))))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addComponent(btnLogOut))
                .addGap(47, 47, 47)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lblBudgets)
                .addGap(18, 18, 18)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudget1)
                    .addComponent(btnCreate1)
                    .addComponent(btnEdit1)
                    .addComponent(btnDelete1))
                .addGap(38, 38, 38)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudget2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudget2)
                    .addComponent(btnCreate2)
                    .addComponent(btnEdit2)
                    .addComponent(btnDelete2))
                .addGap(47, 47, 47)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBudget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBudget3)
                    .addComponent(btnCreate3)
                    .addComponent(btnEdit3)
                    .addComponent(btnDelete3))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        //opens create budget jframe for slot 1
        CreateBudget create = new CreateBudget();
        create.setVisible(true);
        create.setUser(lblUser.getText());
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void btnCreate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate2ActionPerformed
        //opens create budget jframe for slot 1
        CreateBudget create = new CreateBudget();
        create.setVisible(true);
        create.setUser(lblUser.getText());
    }//GEN-LAST:event_btnCreate2ActionPerformed

    private void btnCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate3ActionPerformed
       //opens create budget jframe for slot 1
        CreateBudget create = new CreateBudget();
        create.setVisible(true);
        create.setUser(lblUser.getText());
    }//GEN-LAST:event_btnCreate3ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
       
        try 
       {
           //writes budget name to current budget textfile
           PrintWriter outFile = new PrintWriter
        (new FileWriter("/users/SebastiandeRooy/FinBud/CurrentBudget.txt"));
            outFile.print(txtBudget1.getText());
            outFile.close();
       } catch (IOException e)
       {
           System.out.println("Error");
       }
       
        //opens budgeUI jframe
       BudgetUI budget = new BudgetUI();
       budget.setVisible(true);
       dispose();
           
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        String databaseURL = "jdbc:ucanaccess:///Users/SebastiandeRooy/FinBud/FinBudDB.accdb";
        int id = 0;
        try {
            Connection connection = DriverManager.getConnection(databaseURL);
            
            System.out.println("Connected");
            
            Statement state = connection.createStatement();
            
            
 
            
            //gets budget ID
            Budget budget = new Budget(txtBudget1.getText());
            id = budget.getID();
            System.out.println(id);
            System.out.println(txtBudget1.getText());
            
            //deletes relationships between user and budget
            String sql = "DELETE FROM tblID WHERE BUDGETID = " + id + "";
            
            int row = state.executeUpdate(sql);
            
            if (row > 0)
            {
                System.out.println("Completed");
            }
            
            //deletes budget from database
            sql = "DELETE FROM tblBudget WHERE BUDGETNAME = '" + txtBudget1.getText() + "'";
            
            
            row = state.executeUpdate(sql);
            
            if (row > 0)
            {
                System.out.println("Completed");
            }
            
            
            
            
            
        } catch (SQLException e)
        {
            Logger.getLogger(DBUI.class.getName()).log(Level.SEVERE, null, e);
        }
        
        //resets profile jframe after deleting budget
        Profile profile = new Profile();
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        try 
        {
            //writes budget name to current budget textfile
           PrintWriter outFile = new PrintWriter
        (new FileWriter("/users/SebastiandeRooy/FinBud/CurrentBudget.txt"));
            outFile.print(txtBudget2.getText());
            outFile.close();
       } catch (IOException e)
       {
           System.out.println("Error");
       }
       
        //opens budgeUI jframe
       BudgetUI budget = new BudgetUI();
       budget.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void btnEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit3ActionPerformed
        try 
        {
            //writes budget name to current budget textfile
           PrintWriter outFile = new PrintWriter
        (new FileWriter("/users/SebastiandeRooy/FinBud/CurrentBudget.txt"));
            outFile.print(txtBudget3.getText());
            outFile.close();
       } catch (IOException e)
       {
           System.out.println("Error");
       }
       
        //opens budgeUI jframe
       BudgetUI budget = new BudgetUI();
       budget.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnEdit3ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        //closes jframe and program
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnCreate2;
    private javax.swing.JButton btnCreate3;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnDelete3;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnEdit3;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblBudget1;
    private javax.swing.JLabel lblBudget2;
    private javax.swing.JLabel lblBudget3;
    private javax.swing.JLabel lblBudgets;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JTextField txtBudget1;
    private javax.swing.JTextField txtBudget2;
    private javax.swing.JTextField txtBudget3;
    // End of variables declaration//GEN-END:variables
}
